version: '3.8'
services:
  db:
    container_name: postgres-way
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
  redis:
    container_name: redis-way
    image: redis:latest
    restart: always
    ports:
      - 6379:6379